### PR TITLE
Draft 14

### LINKED ISSUE #294: Remove support for Batch endpoint
OpenId4VCI removed batch endpoint and merged some of its functionality to the the credential endpoint.

- [x] Remove support for batch endpoint
- [x] Update support for credential endpoint to provide the ability to request a single `credential_configuration_id` with zero or more proofs

### LINKED ISSUE #295: Remove CWT Proofs
OpenId4VCI will remove CWT proof types

### LINKED ISSUE #309: Support mulitple proofs to the Credential Endpoint
After draft 13 and the removal of batch endpoint, Credential endpoint was updated to receive either a single proof (of possession) or multiple proofs. In the later case, multiple credentials (single `credential_configuration_id`, same dataset, different device keys) should be returned to the response.

- [x] Add a new attribute to issuer's metadata named `batch_credential_issuance`. Attribute is optional and contains a single attribute `batch_size` which is required. [Details](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-credential-issuer-metadata)
- [x] Change Credential Request to contain either a `proof` or a `proofs` attribute (not both). [Details](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-credential-request)
- [x] Simplify the internal hierarchy that represents a credential request. The `Single` and `Batch` instances are no longer needed.
- [x] Change the issuance interface to allow caller to pass one or more `PopSigner` 
- [x] In the later case, check metadata `batch_credential_issuance`

### LINKED ISSUE #313: Support authorization_details in token endpoint
OpenId4VCI specification [proposes](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-14.html#section-6.1.1) the use of authorization_details when posting a request for an access token in the token endpoint. 

- [ ] Support authorization_details in token endpoint in case of Pre-Authorization code flow
- [ ] Support authorization_details in token endpoint in case of Authorization code flow

### LINKED ISSUE #316: Support retrieving multiple credentials for a single transaction_id
With draft 14, OpenId4VCI foresees that credential response may contain one of the mutually exclusive attributes:
- `credential`
- `transaction_id` 
- `credentials`

Especially, in case of `transaction_id` there is the possibility that corresponds to one or multiple credentials (depending on the request placed).

We need to support in the library the ability to exchange a single `transaction_id` for one or more credentials

### LINKED ISSUE #320: Support issued credentials in the form of String and/or Json Object
In the credential response (or in the deferred response), one or more credentials can be returned.

In VCI , draft 13 & draft14, it states:

> `credential` : It MAY be a string or an object, depending on the Credential Format.

Currently library supports only the string option.

### LINKED ISSUE #323: Remove `interval` from grant `pre-authorized_code` offer
In draft 14, attribute `interval` which used to be part of `pre-authorized_code` grant (of a credential offer) has been removed.

### LINKED ISSUE #325: Deprecate `RequestIssuance.requestSingle`
With draft 14, the credential endpoint can receive zero, one or more proofs.
The `RequestIssuance` interface currently contains two methods 

```kotlin
interface RequestIssuance {

    suspend fun AuthorizedRequest.requestSingle(
        requestPayload: IssuanceRequestPayload,
        popSigner: PopSigner?,
    ): Result<AuthorizedRequestAnd<SubmissionOutcome>> =
        request(requestPayload, popSigner?.let(::listOf).orEmpty())

    suspend fun AuthorizedRequest.request(
        requestPayload: IssuanceRequestPayload,
        popSigners: List<PopSigner> = emptyList(),
    ): Result<AuthorizedRequestAnd<SubmissionOutcome>>
}
```

We can keep just the second function for all cases. For now, we should deprecate the first

### PR DESCRIPTION
**Pull request by babisRoutis**
This PR prepares for the next major release of the library that would support draft14

- [x] Remove CWT proofs
- [x] Remove batch endpoint
- [x] Multiple proofs to credential request (Batch issuance for the same `credential_configuration_id`)
- [x] Retrieve multiple credentials from deferred endpoint
- [x] `notification_id` applicable to `credentials` issued (that's a draft 15 feature needed. addresses an inconsistency of draft14)
- [x] Issued credential could be either String or/and JSON Object 
- [x] Remove `interval` attribute from `pre-authorized_code` grant 
- [x] Support `authorization_details` to token request
- [x] Deprecate `RequestIssuance.requestSingle`

Closes #309 
Closes #295 
Closes #294 
Closes #316 
Closes #320 
Closes #323 
Closes #313 
Closes #325

### CODE REVIEW

**Comment by babisRoutis** [comment]
@vafeini Added in scope #316 

We need to 
a) Re-work the response of the deferred endpoint, since now a transaction_id corresponds to one or more credentials
b) Re-work `IssuedCredential`. The `IssuedCredential.Deferred` must be removed
c) Re-work on the SubmissionOutcome. We need to add `Sumbission.SuccessDeferred`

**Comment by babisRoutis** [comment]
The following change was necessary:

Submission outcome has now three possible states: Success (or Issued), Deferred, Failed.

```kotlin
sealed interface SubmissionOutcome : java.io.Serializable {

    /**
     * State that denotes the successful submission of an issuance request
     * @param credentials The outcome of the issuance request.
     * If the issuance request was a batch request, it will contain the results of each issuance request.
     * If it was a single issuance request list will contain only one result.
     */
    data class Success(val credentials: List<IssuedCredential>) : SubmissionOutcome

    /**
     * Credential could not be issued immediately. An identifier is returned from server to be used later on
     * to request the credential from issuer's Deferred Credential Endpoint.
     *
     * @param transactionId  A string identifying a Deferred Issuance transaction.
     */
    data class Deferred(val transactionId: TransactionId) : SubmissionOutcome

    /**
     * State that denotes that the credential issuance request has failed
     *
     * @param error The error that caused the failure of the request
     */
    data class Failed(val error: CredentialIssuanceError) : SubmissionOutcome
}
```

**Comment by babisRoutis** [comment]
It seems that in d15, `notification_id` will be pertinent to the `credentials` array. That is, each notification event will be associated, not with a single credential but, to the `credentials` array.


Thus, submission outcome & and the deferred outcome need to change once more

```kotlin
sealed interface SubmissionOutcome : java.io.Serializable {

    /**
     * State that denotes the successful submission of an issuance request
     * @param credentials The outcome of the issuance request.
     * If the issuance request was a batch request, it will contain the results of each issuance request.
     * If it was a single issuance request list will contain only one result.
     *
     * @param credentials The credentials issued
     * @param notificationId The identifier to be used in issuer's notification endpoint.
     */
    data class Success(
        val credentials: List<IssuedCredential>,
        val notificationId: NotificationId?,
    ) : SubmissionOutcome {
        init {
            require(credentials.isNotEmpty()) { "credentials must not be empty" }
        }
    }

    /**
     * Credential could not be issued immediately. An identifier is returned from server to be used later on
     * to request the credential from issuer's Deferred Credential Endpoint.
     *
     * @param transactionId  A string identifying a Deferred Issuance transaction.
     */
    data class Deferred(val transactionId: TransactionId) : SubmissionOutcome

    /**
     * State that denotes that the credential issuance request has failed
     *
     * @param error The error that caused the failure of the request
     */
    data class Failed(val error: CredentialIssuanceError) : SubmissionOutcome
}
```

**Comment by babisRoutis** [comment]
To support issued credential both as string and as JSON object the following changes were introduced

```kotlin
sealed interface Credential {
    @JvmInline
    value class Str(val value: String) : Credential {
        override fun toString(): String = value
    }

    @JvmInline
    value class Json(val value: JsonObject) : Credential {
        override fun toString(): String = value.toString()
    }
}

data class IssuedCredential(
    val credential: Credential,
    val additionalInfo: JsonObject?,
)
```

PS: The `additionalInfo` is for future use (d15).

**Comment by babisRoutis** [comment]
There was an issue when interacting with an (draft 13) issuer with regards to the use of not supported proof types.

In particular, library was failing to resolve issuer metadata for configurations that were using proof types other than `jwt` & `ldp_vp`. In draft 13, issuer could use `cwt` proof type, which was removed.

To fix this, a new member was introduced to `ProofTypeMeta` 

```kotlin
sealed interface ProofTypeMeta : Serializable {
    data class Jwt(val algorithms: List<JWSAlgorithm>) : ProofTypeMeta {
        init {
            require(algorithms.isNotEmpty()) { "Supported algorithms in case of JWT cannot be empty" }
        }
    }

    data object LdpVp : ProofTypeMeta {
        private fun readResolve(): Any = LdpVp
    }

    data class Unsupported(val type: String) : ProofTypeMeta
}
```
Now, during issuer metadata resolution, proof types that are not supported by library are mapped to `ProofTypeMeta.Unsupported` .  

In this way, caller may have the opportunity to be aware that issuer requires some kind of proofs that are not supported by the library.

**Comment by babisRoutis** [comment]
@vafeini Please remember to rebase main. Some test fixes where added

**Review by dzarras — APPROVED** [review]

**Pull request merged**
